# Generated by Django 4.0.6 on 2022-09-12 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя проекта')),
                ('link', models.URLField(max_length=255, verbose_name='Ссылка на репозиториий')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Заметка')),
                ('create_data', models.DateTimeField(verbose_name='Создана')),
                ('update_data', models.DateTimeField(verbose_name='Обновлена')),
                ('active', models.BooleanField(verbose_name='Активно')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='todolist.project')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
